services:
  - type: static
    name: e-tet-front
    env: static
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_API_URL
        # Substitua pela URL da sua API no Render (ex: https://e-tet-api.onrender.com)
        value: https://e-tet-api.onrender.com
    routes:
      # Regras de reescrita para Single Page Application (Vue Router)
      - type: rewrite
        source: /*
        destination: /index.html
